### ISSUE TITLE
About Page Fix

### ISSUE THREAD

**Issue by bnleft** [codecoogs/web#12]
- Increase performance, accessibility, and SEO
- I recommend using Lighthouse or any better website analysis tool

![image](https://github.com/codecoogs/web/assets/80173797/44699729-429e-45ae-a152-2c8bfefed959)

**Comment by bnleft** [comment]
suggestion: replace gifs with well encoded mp4 videos

**Comment by ramirezfernando** [comment]
Hey @bnleft, I'm currently working on this. Could you assign this to me?
